# docker-compose.seed-test.yml

name: skycom_seed_test
services:
  web:
    build: .
    command: bash -c "sleep 5 && rm -f tmp/pids/server.pid && bundle exec rails db:prepare"
    environment:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    # image: redis:7.2-alpine
    image: valkey/valkey:9.1-alpine
    ports:
      - "6379:6379"
