name: skycom_rspec_test

services:
  web:
    build: .
    # command optimized for test environment
    command: bash -c "sleep 5 && rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rspec"
    environment:
      RAILS_ENV: test
      SKIP_TEST_RUN_SEED: false
      TEST_RUN_INSIDE_DOCKER: true
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    depends_on:
      - postgres
      - mock-api

  job:
    build: .
    command: bash -c "sleep 20 && bundle exec rails db:prepare && bin/jobs"
    environment:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    depends_on:
      - web

  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    # No volume mapping here to ensure a fresh DB state for every test run
    ports:
      - "5432:5432"

  redis:
    # image: redis:7.2-alpine
    image: valkey/valkey:9.1-alpine
    ports:
      - "6379:6379"

  websocket:
    image: centrifugo/centrifugo:v5
    ports:
      - "8000:8000"
    command: centrifugo --client_insecure=false --api_insecure=false
    environment:
      # 🚀 Include "null" to allow SharedWorker Data URLs
      CENTRIFUGO_ALLOWED_ORIGINS: "http://localhost:3000 http://127.0.0.1:3000 http://web:3000 null"
      # Administrative Backend API Token (Matches Rails CENTRIFUGO_API_KEY)
      CENTRIFUGO_API_KEY: "skycom_super_secret_api_key_2026"
      # Secure Verification Engine Token (Matches Rails CENTRIFUGO_TOKEN_HMAC_SECRET_KEY)
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: "skycom_jwt_hmac_secret_token_key_2026"
      # Enable Centrifugo Administrative Dashboard Interface
      CENTRIFUGO_ADMIN: "true"
      CENTRIFUGO_ADMIN_PASSWORD: "Password@123"
      CENTRIFUGO_ADMIN_SECRET: "Password@123"

  mock-api:
    image: golang:1.22-alpine
    working_dir: /go/src/app
    # Line A: Mount your local folder inside the container
    volumes:
      - ./mock_api:/go/src/app
    command: go run main.go
    ports:
      - "4000:4000"
volumes:
  sqlite_storage: