# docker-compose.yml

# docker compose up -d
# RAILS_MASTER_KEY=$(cat config/master.key) docker compose up -d
# RAILS_MASTER_KEY=$(cat config/master.key) docker compose -f docker-compose.seed-test.yml up --abort-on-container-exit --exit-code-from web --attach web
# RAILS_MASTER_KEY=$(cat config/master.key) docker compose -f docker-compose.rspec-test.yml up --abort-on-container-exit --exit-code-from web --attach web

name: skycom_development
services:
  web:
    build: .
    command: bash -c "sleep 30 && rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails assets:precompile && bundle exec thrust bin/rails s"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - pulse_postgres
      - minio
      - websocket

  job:
    build: .
    command: bash -c "sleep 15 && bundle exec rails db:prepare && bin/jobs"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    depends_on:
      - web
      - pulse_postgres
      - websocket

  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
 
  # MinIO Service
  minio:
    image: minio/minio:latest
    ports:
      # MinIO API port
      - "9000:9000" 
      # MinIO Console/UI port
      - "9001:9001" 
    environment:
      # MinIO root user credentials
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      # Data persistence
      - minio_data:/data 
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  create_buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy # Wait for MinIO to be fully ready
    # Wait for the MinIO API to be available and then execute the command
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio_host http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio_host/skycom-development;
      /usr/bin/mc policy set download minio_host/skycom-development;
      /usr/bin/mc mb minio_host/skycom-production;
      /usr/bin/mc policy set download minio_host/skycom-production;
      /usr/bin/mc exit
      "
    # This service runs once and exits successfully
    # profiles: ["no-start"] # Optional: Prevents this service from running on 'docker compose up' by default, if you only want it on explicit 'docker compose run'

  redis:
    # image: redis:7.2-alpine
    image: valkey/valkey:9.1-alpine
    # container_name: redis_central_cache
    # --appendonly yes ensures your flash sale data is saved to disk continuously
    # command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-secretpassword}"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  openobserve:
    image: openobserve/openobserve:latest
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=Password@123
    ports:
      - "5080:5080" # UI and OTel endpoint
    volumes:
      - openobserve_data:/data

  # Centrifugo Real-time Core WebSocket Engine
  websocket:
    image: centrifugo/centrifugo:v5
    volumes:
      - websocket_data:/centrifugo
    ports:
      - "8000:8000"
    command: centrifugo --client_insecure=false --api_insecure=false
    environment:
      CENTRIFUGO_ALLOWED_ORIGINS: "http://localhost:3000"
      # Administrative Backend API Token (Matches Rails CENTRIFUGO_API_KEY)
      CENTRIFUGO_API_KEY: "skycom_super_secret_api_key_2026"
      # Secure Verification Engine Token (Matches Rails CENTRIFUGO_TOKEN_HMAC_SECRET_KEY)
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: "skycom_jwt_hmac_secret_token_key_2026"
      # Enable Centrifugo Administrative Dashboard Interface
      CENTRIFUGO_ADMIN: "true"
      CENTRIFUGO_ADMIN_PASSWORD: "Password@123"
      CENTRIFUGO_ADMIN_SECRET: "Password@123"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
  mongo_data:
  grafana_data:
  minio_data:
  sqlite_storage:
  redis_data:
  openobserve_data:
  websocket_data:
