name: skycom_rspec_test

services:
  web:
    build: .
    # command optimized for test environment
    command: bash -c "sleep 5 && rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rspec"
    environment:
      RAILS_ENV: test
      SKIP_TEST_RUN_SEED: false
      TEST_RUN_INSIDE_DOCKER: true
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    depends_on:
      - postgres
      - pulse_postgres

  job:
    build: .
    command: bash -c "sleep 20 && bundle exec rails db:prepare && bin/jobs"
    environment:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - sqlite_storage:/rails/storage
    depends_on:
      - web

  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    # No volume mapping here to ensure a fresh DB state for every test run
    ports:
      - "5432:5432"

  pulse_postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Exposed on 5433 host-side to avoid conflict with main postgres

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

volumes:
  sqlite_storage: