require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cart_groups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CartGroup. As you add validations to CartGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CartGroup.create! valid_attributes
      get cart_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cart_group = CartGroup.create! valid_attributes
      get cart_group_url(cart_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cart_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cart_group = CartGroup.create! valid_attributes
      get edit_cart_group_url(cart_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CartGroup" do
        expect {
          post cart_groups_url, params: { cart_group: valid_attributes }
        }.to change(CartGroup, :count).by(1)
      end

      it "redirects to the created cart_group" do
        post cart_groups_url, params: { cart_group: valid_attributes }
        expect(response).to redirect_to(cart_group_url(CartGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CartGroup" do
        expect {
          post cart_groups_url, params: { cart_group: invalid_attributes }
        }.to change(CartGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cart_groups_url, params: { cart_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cart_group" do
        cart_group = CartGroup.create! valid_attributes
        patch cart_group_url(cart_group), params: { cart_group: new_attributes }
        cart_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cart_group" do
        cart_group = CartGroup.create! valid_attributes
        patch cart_group_url(cart_group), params: { cart_group: new_attributes }
        cart_group.reload
        expect(response).to redirect_to(cart_group_url(cart_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cart_group = CartGroup.create! valid_attributes
        patch cart_group_url(cart_group), params: { cart_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cart_group" do
      cart_group = CartGroup.create! valid_attributes
      expect {
        delete cart_group_url(cart_group)
      }.to change(CartGroup, :count).by(-1)
    end

    it "redirects to the cart_groups list" do
      cart_group = CartGroup.create! valid_attributes
      delete cart_group_url(cart_group)
      expect(response).to redirect_to(cart_groups_url)
    end
  end
end
