require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/document_groups", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DocumentGroup. As you add validations to DocumentGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DocumentGroup.create! valid_attributes
      get document_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      document_group = DocumentGroup.create! valid_attributes
      get document_group_url(document_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_document_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      document_group = DocumentGroup.create! valid_attributes
      get edit_document_group_url(document_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DocumentGroup" do
        expect {
          post document_groups_url, params: { document_group: valid_attributes }
        }.to change(DocumentGroup, :count).by(1)
      end

      it "redirects to the created document_group" do
        post document_groups_url, params: { document_group: valid_attributes }
        expect(response).to redirect_to(document_group_url(DocumentGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DocumentGroup" do
        expect {
          post document_groups_url, params: { document_group: invalid_attributes }
        }.to change(DocumentGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post document_groups_url, params: { document_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested document_group" do
        document_group = DocumentGroup.create! valid_attributes
        patch document_group_url(document_group), params: { document_group: new_attributes }
        document_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the document_group" do
        document_group = DocumentGroup.create! valid_attributes
        patch document_group_url(document_group), params: { document_group: new_attributes }
        document_group.reload
        expect(response).to redirect_to(document_group_url(document_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        document_group = DocumentGroup.create! valid_attributes
        patch document_group_url(document_group), params: { document_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested document_group" do
      document_group = DocumentGroup.create! valid_attributes
      expect {
        delete document_group_url(document_group)
      }.to change(DocumentGroup, :count).by(-1)
    end

    it "redirects to the document_groups list" do
      document_group = DocumentGroup.create! valid_attributes
      delete document_group_url(document_group)
      expect(response).to redirect_to(document_groups_url)
    end
  end
end
