require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exam_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ExamAppointment. As you add validations to ExamAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExamAppointment.create! valid_attributes
      get exam_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      exam_appointment = ExamAppointment.create! valid_attributes
      get exam_appointment_url(exam_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exam_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      exam_appointment = ExamAppointment.create! valid_attributes
      get edit_exam_appointment_url(exam_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExamAppointment" do
        expect {
          post exam_appointments_url, params: { exam_appointment: valid_attributes }
        }.to change(ExamAppointment, :count).by(1)
      end

      it "redirects to the created exam_appointment" do
        post exam_appointments_url, params: { exam_appointment: valid_attributes }
        expect(response).to redirect_to(exam_appointment_url(ExamAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExamAppointment" do
        expect {
          post exam_appointments_url, params: { exam_appointment: invalid_attributes }
        }.to change(ExamAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exam_appointments_url, params: { exam_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exam_appointment" do
        exam_appointment = ExamAppointment.create! valid_attributes
        patch exam_appointment_url(exam_appointment), params: { exam_appointment: new_attributes }
        exam_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the exam_appointment" do
        exam_appointment = ExamAppointment.create! valid_attributes
        patch exam_appointment_url(exam_appointment), params: { exam_appointment: new_attributes }
        exam_appointment.reload
        expect(response).to redirect_to(exam_appointment_url(exam_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        exam_appointment = ExamAppointment.create! valid_attributes
        patch exam_appointment_url(exam_appointment), params: { exam_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested exam_appointment" do
      exam_appointment = ExamAppointment.create! valid_attributes
      expect {
        delete exam_appointment_url(exam_appointment)
      }.to change(ExamAppointment, :count).by(-1)
    end

    it "redirects to the exam_appointments list" do
      exam_appointment = ExamAppointment.create! valid_attributes
      delete exam_appointment_url(exam_appointment)
      expect(response).to redirect_to(exam_appointments_url)
    end
  end
end
