require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/facility_group_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FacilityGroupAppointment. As you add validations to FacilityGroupAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FacilityGroupAppointment.create! valid_attributes
      get facility_group_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
      get facility_group_appointment_url(facility_group_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_facility_group_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
      get edit_facility_group_appointment_url(facility_group_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FacilityGroupAppointment" do
        expect {
          post facility_group_appointments_url, params: { facility_group_appointment: valid_attributes }
        }.to change(FacilityGroupAppointment, :count).by(1)
      end

      it "redirects to the created facility_group_appointment" do
        post facility_group_appointments_url, params: { facility_group_appointment: valid_attributes }
        expect(response).to redirect_to(facility_group_appointment_url(FacilityGroupAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FacilityGroupAppointment" do
        expect {
          post facility_group_appointments_url, params: { facility_group_appointment: invalid_attributes }
        }.to change(FacilityGroupAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post facility_group_appointments_url, params: { facility_group_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested facility_group_appointment" do
        facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
        patch facility_group_appointment_url(facility_group_appointment), params: { facility_group_appointment: new_attributes }
        facility_group_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the facility_group_appointment" do
        facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
        patch facility_group_appointment_url(facility_group_appointment), params: { facility_group_appointment: new_attributes }
        facility_group_appointment.reload
        expect(response).to redirect_to(facility_group_appointment_url(facility_group_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
        patch facility_group_appointment_url(facility_group_appointment), params: { facility_group_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested facility_group_appointment" do
      facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
      expect {
        delete facility_group_appointment_url(facility_group_appointment)
      }.to change(FacilityGroupAppointment, :count).by(-1)
    end

    it "redirects to the facility_group_appointments list" do
      facility_group_appointment = FacilityGroupAppointment.create! valid_attributes
      delete facility_group_appointment_url(facility_group_appointment)
      expect(response).to redirect_to(facility_group_appointments_url)
    end
  end
end
