require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/facility_groups", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FacilityGroup. As you add validations to FacilityGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FacilityGroup.create! valid_attributes
      get facility_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      facility_group = FacilityGroup.create! valid_attributes
      get facility_group_url(facility_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_facility_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      facility_group = FacilityGroup.create! valid_attributes
      get edit_facility_group_url(facility_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FacilityGroup" do
        expect {
          post facility_groups_url, params: { facility_group: valid_attributes }
        }.to change(FacilityGroup, :count).by(1)
      end

      it "redirects to the created facility_group" do
        post facility_groups_url, params: { facility_group: valid_attributes }
        expect(response).to redirect_to(facility_group_url(FacilityGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FacilityGroup" do
        expect {
          post facility_groups_url, params: { facility_group: invalid_attributes }
        }.to change(FacilityGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post facility_groups_url, params: { facility_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested facility_group" do
        facility_group = FacilityGroup.create! valid_attributes
        patch facility_group_url(facility_group), params: { facility_group: new_attributes }
        facility_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the facility_group" do
        facility_group = FacilityGroup.create! valid_attributes
        patch facility_group_url(facility_group), params: { facility_group: new_attributes }
        facility_group.reload
        expect(response).to redirect_to(facility_group_url(facility_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        facility_group = FacilityGroup.create! valid_attributes
        patch facility_group_url(facility_group), params: { facility_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested facility_group" do
      facility_group = FacilityGroup.create! valid_attributes
      expect {
        delete facility_group_url(facility_group)
      }.to change(FacilityGroup, :count).by(-1)
    end

    it "redirects to the facility_groups list" do
      facility_group = FacilityGroup.create! valid_attributes
      delete facility_group_url(facility_group)
      expect(response).to redirect_to(facility_groups_url)
    end
  end
end
