require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inventory_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # InventoryItem. As you add validations to InventoryItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InventoryItem.create! valid_attributes
      get inventory_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inventory_item = InventoryItem.create! valid_attributes
      get inventory_item_url(inventory_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inventory_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      inventory_item = InventoryItem.create! valid_attributes
      get edit_inventory_item_url(inventory_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InventoryItem" do
        expect {
          post inventory_items_url, params: { inventory_item: valid_attributes }
        }.to change(InventoryItem, :count).by(1)
      end

      it "redirects to the created inventory_item" do
        post inventory_items_url, params: { inventory_item: valid_attributes }
        expect(response).to redirect_to(inventory_item_url(InventoryItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InventoryItem" do
        expect {
          post inventory_items_url, params: { inventory_item: invalid_attributes }
        }.to change(InventoryItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post inventory_items_url, params: { inventory_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inventory_item" do
        inventory_item = InventoryItem.create! valid_attributes
        patch inventory_item_url(inventory_item), params: { inventory_item: new_attributes }
        inventory_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inventory_item" do
        inventory_item = InventoryItem.create! valid_attributes
        patch inventory_item_url(inventory_item), params: { inventory_item: new_attributes }
        inventory_item.reload
        expect(response).to redirect_to(inventory_item_url(inventory_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        inventory_item = InventoryItem.create! valid_attributes
        patch inventory_item_url(inventory_item), params: { inventory_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inventory_item" do
      inventory_item = InventoryItem.create! valid_attributes
      expect {
        delete inventory_item_url(inventory_item)
      }.to change(InventoryItem, :count).by(-1)
    end

    it "redirects to the inventory_items list" do
      inventory_item = InventoryItem.create! valid_attributes
      delete inventory_item_url(inventory_item)
      expect(response).to redirect_to(inventory_items_url)
    end
  end
end
