require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/notification_group_appointments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NotificationGroupAppointment. As you add validations to NotificationGroupAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NotificationGroupAppointment.create! valid_attributes
      get notification_group_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
      get notification_group_appointment_url(notification_group_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_notification_group_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
      get edit_notification_group_appointment_url(notification_group_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NotificationGroupAppointment" do
        expect {
          post notification_group_appointments_url, params: { notification_group_appointment: valid_attributes }
        }.to change(NotificationGroupAppointment, :count).by(1)
      end

      it "redirects to the created notification_group_appointment" do
        post notification_group_appointments_url, params: { notification_group_appointment: valid_attributes }
        expect(response).to redirect_to(notification_group_appointment_url(NotificationGroupAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NotificationGroupAppointment" do
        expect {
          post notification_group_appointments_url, params: { notification_group_appointment: invalid_attributes }
        }.to change(NotificationGroupAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post notification_group_appointments_url, params: { notification_group_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested notification_group_appointment" do
        notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
        patch notification_group_appointment_url(notification_group_appointment), params: { notification_group_appointment: new_attributes }
        notification_group_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the notification_group_appointment" do
        notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
        patch notification_group_appointment_url(notification_group_appointment), params: { notification_group_appointment: new_attributes }
        notification_group_appointment.reload
        expect(response).to redirect_to(notification_group_appointment_url(notification_group_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
        patch notification_group_appointment_url(notification_group_appointment), params: { notification_group_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested notification_group_appointment" do
      notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
      expect {
        delete notification_group_appointment_url(notification_group_appointment)
      }.to change(NotificationGroupAppointment, :count).by(-1)
    end

    it "redirects to the notification_group_appointments list" do
      notification_group_appointment = NotificationGroupAppointment.create! valid_attributes
      delete notification_group_appointment_url(notification_group_appointment)
      expect(response).to redirect_to(notification_group_appointments_url)
    end
  end
end
