require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/period_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PeriodAppointment. As you add validations to PeriodAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PeriodAppointment.create! valid_attributes
      get period_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      period_appointment = PeriodAppointment.create! valid_attributes
      get period_appointment_url(period_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_period_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      period_appointment = PeriodAppointment.create! valid_attributes
      get edit_period_appointment_url(period_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PeriodAppointment" do
        expect {
          post period_appointments_url, params: { period_appointment: valid_attributes }
        }.to change(PeriodAppointment, :count).by(1)
      end

      it "redirects to the created period_appointment" do
        post period_appointments_url, params: { period_appointment: valid_attributes }
        expect(response).to redirect_to(period_appointment_url(PeriodAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PeriodAppointment" do
        expect {
          post period_appointments_url, params: { period_appointment: invalid_attributes }
        }.to change(PeriodAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post period_appointments_url, params: { period_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested period_appointment" do
        period_appointment = PeriodAppointment.create! valid_attributes
        patch period_appointment_url(period_appointment), params: { period_appointment: new_attributes }
        period_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the period_appointment" do
        period_appointment = PeriodAppointment.create! valid_attributes
        patch period_appointment_url(period_appointment), params: { period_appointment: new_attributes }
        period_appointment.reload
        expect(response).to redirect_to(period_appointment_url(period_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        period_appointment = PeriodAppointment.create! valid_attributes
        patch period_appointment_url(period_appointment), params: { period_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested period_appointment" do
      period_appointment = PeriodAppointment.create! valid_attributes
      expect {
        delete period_appointment_url(period_appointment)
      }.to change(PeriodAppointment, :count).by(-1)
    end

    it "redirects to the period_appointments list" do
      period_appointment = PeriodAppointment.create! valid_attributes
      delete period_appointment_url(period_appointment)
      expect(response).to redirect_to(period_appointments_url)
    end
  end
end
