require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/policy_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PolicyAppointment. As you add validations to PolicyAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PolicyAppointment.create! valid_attributes
      get policy_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      policy_appointment = PolicyAppointment.create! valid_attributes
      get policy_appointment_url(policy_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_policy_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      policy_appointment = PolicyAppointment.create! valid_attributes
      get edit_policy_appointment_url(policy_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PolicyAppointment" do
        expect {
          post policy_appointments_url, params: { policy_appointment: valid_attributes }
        }.to change(PolicyAppointment, :count).by(1)
      end

      it "redirects to the created policy_appointment" do
        post policy_appointments_url, params: { policy_appointment: valid_attributes }
        expect(response).to redirect_to(policy_appointment_url(PolicyAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PolicyAppointment" do
        expect {
          post policy_appointments_url, params: { policy_appointment: invalid_attributes }
        }.to change(PolicyAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post policy_appointments_url, params: { policy_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested policy_appointment" do
        policy_appointment = PolicyAppointment.create! valid_attributes
        patch policy_appointment_url(policy_appointment), params: { policy_appointment: new_attributes }
        policy_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the policy_appointment" do
        policy_appointment = PolicyAppointment.create! valid_attributes
        patch policy_appointment_url(policy_appointment), params: { policy_appointment: new_attributes }
        policy_appointment.reload
        expect(response).to redirect_to(policy_appointment_url(policy_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        policy_appointment = PolicyAppointment.create! valid_attributes
        patch policy_appointment_url(policy_appointment), params: { policy_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested policy_appointment" do
      policy_appointment = PolicyAppointment.create! valid_attributes
      expect {
        delete policy_appointment_url(policy_appointment)
      }.to change(PolicyAppointment, :count).by(-1)
    end

    it "redirects to the policy_appointments list" do
      policy_appointment = PolicyAppointment.create! valid_attributes
      delete policy_appointment_url(policy_appointment)
      expect(response).to redirect_to(policy_appointments_url)
    end
  end
end
