require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/product_appointments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductAppointment. As you add validations to ProductAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductAppointment.create! valid_attributes
      get product_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      product_appointment = ProductAppointment.create! valid_attributes
      get product_appointment_url(product_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_product_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      product_appointment = ProductAppointment.create! valid_attributes
      get edit_product_appointment_url(product_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductAppointment" do
        expect {
          post product_appointments_url, params: { product_appointment: valid_attributes }
        }.to change(ProductAppointment, :count).by(1)
      end

      it "redirects to the created product_appointment" do
        post product_appointments_url, params: { product_appointment: valid_attributes }
        expect(response).to redirect_to(product_appointment_url(ProductAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductAppointment" do
        expect {
          post product_appointments_url, params: { product_appointment: invalid_attributes }
        }.to change(ProductAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_appointments_url, params: { product_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested product_appointment" do
        product_appointment = ProductAppointment.create! valid_attributes
        patch product_appointment_url(product_appointment), params: { product_appointment: new_attributes }
        product_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the product_appointment" do
        product_appointment = ProductAppointment.create! valid_attributes
        patch product_appointment_url(product_appointment), params: { product_appointment: new_attributes }
        product_appointment.reload
        expect(response).to redirect_to(product_appointment_url(product_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_appointment = ProductAppointment.create! valid_attributes
        patch product_appointment_url(product_appointment), params: { product_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested product_appointment" do
      product_appointment = ProductAppointment.create! valid_attributes
      expect {
        delete product_appointment_url(product_appointment)
      }.to change(ProductAppointment, :count).by(-1)
    end

    it "redirects to the product_appointments list" do
      product_appointment = ProductAppointment.create! valid_attributes
      delete product_appointment_url(product_appointment)
      expect(response).to redirect_to(product_appointments_url)
    end
  end
end
