require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_appointments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectAppointment. As you add validations to ProjectAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectAppointment.create! valid_attributes
      get project_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_appointment = ProjectAppointment.create! valid_attributes
      get project_appointment_url(project_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      project_appointment = ProjectAppointment.create! valid_attributes
      get edit_project_appointment_url(project_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectAppointment" do
        expect {
          post project_appointments_url, params: { project_appointment: valid_attributes }
        }.to change(ProjectAppointment, :count).by(1)
      end

      it "redirects to the created project_appointment" do
        post project_appointments_url, params: { project_appointment: valid_attributes }
        expect(response).to redirect_to(project_appointment_url(ProjectAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectAppointment" do
        expect {
          post project_appointments_url, params: { project_appointment: invalid_attributes }
        }.to change(ProjectAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post project_appointments_url, params: { project_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_appointment" do
        project_appointment = ProjectAppointment.create! valid_attributes
        patch project_appointment_url(project_appointment), params: { project_appointment: new_attributes }
        project_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_appointment" do
        project_appointment = ProjectAppointment.create! valid_attributes
        patch project_appointment_url(project_appointment), params: { project_appointment: new_attributes }
        project_appointment.reload
        expect(response).to redirect_to(project_appointment_url(project_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        project_appointment = ProjectAppointment.create! valid_attributes
        patch project_appointment_url(project_appointment), params: { project_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_appointment" do
      project_appointment = ProjectAppointment.create! valid_attributes
      expect {
        delete project_appointment_url(project_appointment)
      }.to change(ProjectAppointment, :count).by(-1)
    end

    it "redirects to the project_appointments list" do
      project_appointment = ProjectAppointment.create! valid_attributes
      delete project_appointment_url(project_appointment)
      expect(response).to redirect_to(project_appointments_url)
    end
  end
end
