require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RoleAppointment. As you add validations to RoleAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RoleAppointment.create! valid_attributes
      get role_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      role_appointment = RoleAppointment.create! valid_attributes
      get role_appointment_url(role_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_role_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      role_appointment = RoleAppointment.create! valid_attributes
      get edit_role_appointment_url(role_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RoleAppointment" do
        expect {
          post role_appointments_url, params: { role_appointment: valid_attributes }
        }.to change(RoleAppointment, :count).by(1)
      end

      it "redirects to the created role_appointment" do
        post role_appointments_url, params: { role_appointment: valid_attributes }
        expect(response).to redirect_to(role_appointment_url(RoleAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RoleAppointment" do
        expect {
          post role_appointments_url, params: { role_appointment: invalid_attributes }
        }.to change(RoleAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post role_appointments_url, params: { role_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_appointment" do
        role_appointment = RoleAppointment.create! valid_attributes
        patch role_appointment_url(role_appointment), params: { role_appointment: new_attributes }
        role_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_appointment" do
        role_appointment = RoleAppointment.create! valid_attributes
        patch role_appointment_url(role_appointment), params: { role_appointment: new_attributes }
        role_appointment.reload
        expect(response).to redirect_to(role_appointment_url(role_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        role_appointment = RoleAppointment.create! valid_attributes
        patch role_appointment_url(role_appointment), params: { role_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_appointment" do
      role_appointment = RoleAppointment.create! valid_attributes
      expect {
        delete role_appointment_url(role_appointment)
      }.to change(RoleAppointment, :count).by(-1)
    end

    it "redirects to the role_appointments list" do
      role_appointment = RoleAppointment.create! valid_attributes
      delete role_appointment_url(role_appointment)
      expect(response).to redirect_to(role_appointments_url)
    end
  end
end
