require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/setting_groups", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SettingGroup. As you add validations to SettingGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SettingGroup.create! valid_attributes
      get setting_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      setting_group = SettingGroup.create! valid_attributes
      get setting_group_url(setting_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_setting_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      setting_group = SettingGroup.create! valid_attributes
      get edit_setting_group_url(setting_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SettingGroup" do
        expect {
          post setting_groups_url, params: { setting_group: valid_attributes }
        }.to change(SettingGroup, :count).by(1)
      end

      it "redirects to the created setting_group" do
        post setting_groups_url, params: { setting_group: valid_attributes }
        expect(response).to redirect_to(setting_group_url(SettingGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SettingGroup" do
        expect {
          post setting_groups_url, params: { setting_group: invalid_attributes }
        }.to change(SettingGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post setting_groups_url, params: { setting_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested setting_group" do
        setting_group = SettingGroup.create! valid_attributes
        patch setting_group_url(setting_group), params: { setting_group: new_attributes }
        setting_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the setting_group" do
        setting_group = SettingGroup.create! valid_attributes
        patch setting_group_url(setting_group), params: { setting_group: new_attributes }
        setting_group.reload
        expect(response).to redirect_to(setting_group_url(setting_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        setting_group = SettingGroup.create! valid_attributes
        patch setting_group_url(setting_group), params: { setting_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested setting_group" do
      setting_group = SettingGroup.create! valid_attributes
      expect {
        delete setting_group_url(setting_group)
      }.to change(SettingGroup, :count).by(-1)
    end

    it "redirects to the setting_groups list" do
      setting_group = SettingGroup.create! valid_attributes
      delete setting_group_url(setting_group)
      expect(response).to redirect_to(setting_groups_url)
    end
  end
end
