require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task_appointments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # TaskAppointment. As you add validations to TaskAppointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaskAppointment.create! valid_attributes
      get task_appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task_appointment = TaskAppointment.create! valid_attributes
      get task_appointment_url(task_appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_appointment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      task_appointment = TaskAppointment.create! valid_attributes
      get edit_task_appointment_url(task_appointment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaskAppointment" do
        expect {
          post task_appointments_url, params: { task_appointment: valid_attributes }
        }.to change(TaskAppointment, :count).by(1)
      end

      it "redirects to the created task_appointment" do
        post task_appointments_url, params: { task_appointment: valid_attributes }
        expect(response).to redirect_to(task_appointment_url(TaskAppointment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaskAppointment" do
        expect {
          post task_appointments_url, params: { task_appointment: invalid_attributes }
        }.to change(TaskAppointment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post task_appointments_url, params: { task_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_appointment" do
        task_appointment = TaskAppointment.create! valid_attributes
        patch task_appointment_url(task_appointment), params: { task_appointment: new_attributes }
        task_appointment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task_appointment" do
        task_appointment = TaskAppointment.create! valid_attributes
        patch task_appointment_url(task_appointment), params: { task_appointment: new_attributes }
        task_appointment.reload
        expect(response).to redirect_to(task_appointment_url(task_appointment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        task_appointment = TaskAppointment.create! valid_attributes
        patch task_appointment_url(task_appointment), params: { task_appointment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task_appointment" do
      task_appointment = TaskAppointment.create! valid_attributes
      expect {
        delete task_appointment_url(task_appointment)
      }.to change(TaskAppointment, :count).by(-1)
    end

    it "redirects to the task_appointments list" do
      task_appointment = TaskAppointment.create! valid_attributes
      delete task_appointment_url(task_appointment)
      expect(response).to redirect_to(task_appointments_url)
    end
  end
end
