require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task_groups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TaskGroup. As you add validations to TaskGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaskGroup.create! valid_attributes
      get task_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task_group = TaskGroup.create! valid_attributes
      get task_group_url(task_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      task_group = TaskGroup.create! valid_attributes
      get edit_task_group_url(task_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaskGroup" do
        expect {
          post task_groups_url, params: { task_group: valid_attributes }
        }.to change(TaskGroup, :count).by(1)
      end

      it "redirects to the created task_group" do
        post task_groups_url, params: { task_group: valid_attributes }
        expect(response).to redirect_to(task_group_url(TaskGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaskGroup" do
        expect {
          post task_groups_url, params: { task_group: invalid_attributes }
        }.to change(TaskGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post task_groups_url, params: { task_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_group" do
        task_group = TaskGroup.create! valid_attributes
        patch task_group_url(task_group), params: { task_group: new_attributes }
        task_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task_group" do
        task_group = TaskGroup.create! valid_attributes
        patch task_group_url(task_group), params: { task_group: new_attributes }
        task_group.reload
        expect(response).to redirect_to(task_group_url(task_group))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        task_group = TaskGroup.create! valid_attributes
        patch task_group_url(task_group), params: { task_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task_group" do
      task_group = TaskGroup.create! valid_attributes
      expect {
        delete task_group_url(task_group)
      }.to change(TaskGroup, :count).by(-1)
    end

    it "redirects to the task_groups list" do
      task_group = TaskGroup.create! valid_attributes
      delete task_group_url(task_group)
      expect(response).to redirect_to(task_groups_url)
    end
  end
end
