/** * @typedef {Object} Metadata - Generic for JSONB columns
 * @property {Object} [key] 
 */

// --- 1. CORE SYSTEM & AUTHENTICATION ---
/** @typedef {Object} User @property {string} id @property {string} email @property {string} password_digest @property {boolean} verified @property {string} provider @property {string} uid @property {string} parent_user_id @property {number} system_role @property {string} username @property {string} first_name @property {string} last_name @property {string} avatar @property {string} phone_number @property {number} country_code @property {string} single_access_token @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} Session @property {string} id @property {string} user_id @property {string} user_agent @property {string} ip_address @property {string} single_access_token @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} SignInToken @property {string} id @property {string} user_id */
/** @typedef {Object} System @property {string} id @property {string} email @property {string} name @property {string} code @property {number} balance_cents @property {number} currency_code @property {number} country_code @property {boolean} active @property {Metadata} metadata @property {string} created_at @property {string} updated_at */

// --- 2. ORGANIZATION STRUCTURE ---
/** @typedef {Object} Company @property {string} id @property {string} user_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} ownership_type @property {number} business_type @property {number} currency_code @property {string} registration_number @property {string} vat_id @property {string} tax_id @property {number} timezone @property {string} address_line_1 @property {string} city @property {string} postal_code @property {number} country_code @property {string} email @property {string} phone_number @property {string} website @property {number} employee_count @property {number} fiscal_year_end_month @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} Branch @property {string} id @property {string} company_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} ownership_type @property {number} business_type @property {number} currency_code @property {string} registration_number @property {string} vat_id @property {string} tax_id @property {number} timezone @property {string} address_line_1 @property {string} city @property {string} postal_code @property {number} country_code @property {string} email @property {string} phone_number @property {string} website @property {number} employee_count @property {number} fiscal_year_end_month @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} Department @property {string} id @property {string} company_id @property {string} category_id @property {string} email @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} Role @property {string} id @property {string} company_id @property {string} branch_id @property {number} model_type @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {string} created_at @property {string} updated_at */
/** @typedef {Object} Policy @property {string} id @property {string} company_id @property {string} branch_id @property {string} name @property {string} description @property {string} code @property {string} resource @property {string} action @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {string} created_at @property {string} updated_at */

// --- 3. PEOPLE & ATTENDANCE ---
/** @typedef {Object} Employee @property {string} id @property {string} company_id @property {string} branch_id @property {string} user_id @property {string} category_id @property {string} email @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} EmployeeGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} email @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} AttendanceDay @property {string} id @property {string} company_id @property {string} branch_id @property {string} employee_id @property {string} logable_type @property {string} logable_id @property {string} period_id @property {string} attendance_date @property {string} check_in @property {string} check_out @property {string} break_start @property {string} break_end @property {number} total_seconds_present @property {number} total_seconds_break @property {number} total_seconds_worked @property {number} total_seconds_overtime @property {number} shift_id @property {number} attendance_status @property {number} recorded_method @property {string} ip_address @property {string} device_id @property {number} location_lat @property {number} location_lng @property {string} notes @property {string} approved_by_type @property {string} approved_by_id @property {string} approved_at @property {string} edited_by_type @property {string} edited_by_id @property {string} edited_at */
/** @typedef {Object} AttendanceLog @property {string} id @property {string} company_id @property {string} branch_id @property {string} customer_id @property {string} logable_type @property {string} logable_id @property {string} period_id @property {string} location @property {string} id_address @property {string} device_info @property {string} notes */
/** @typedef {Object} AttendanceMonth @property {string} id @property {string} company_id @property {string} branch_id @property {string} customer_id @property {string} logable_type @property {string} logable_id @property {string} period_id */
/** @typedef {Object} Shift @property {string} id @property {string} company_id @property {string} branch_id @property {string} period_id @property {string} name @property {string} description @property {Metadata} metadata */

// --- 4. CUSTOMERS & CRM ---
/** @typedef {Object} Customer @property {string} id @property {string} company_id @property {string} branch_id @property {string} user_id @property {string} category_id @property {string} email @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */
/** @typedef {Object} CustomerGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} email @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata @property {string} created_at @property {string} updated_at */

// --- 5. COMMERCE (PRODUCTS, ORDERS, INVOICES) ---
/** @typedef {Object} Product @property {string} id @property {string} company_id @property {string} branch_id @property {string} brand_id @property {string} category_id @property {string} name @property {string} description @property {number} price @property {number} currency_code @property {string} code @property {string} sku @property {string} barcode @property {string} upc @property {string} ean @property {string} manufacturer_code @property {string} serial_number @property {string} batch_number @property {string} expiration_date @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} ProductGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Order @property {string} id @property {string} company_id @property {string} branch_id @property {string} customer_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {string} sku @property {string} barcode @property {string} upc @property {string} ean @property {string} manufacturer_code @property {string} serial_number @property {string} batch_number @property {string} expiration_date @property {number} currency_code @property {number} duration @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} OrderGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} customer_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} currency_code @property {number} duration @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Invoice @property {string} id @property {string} company_id @property {string} branch_id @property {string} order_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} currency_code @property {number} duration @property {string} number @property {number} total_price @property {string} due_date @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Payment @property {string} id @property {string} company_id @property {string} branch_id @property {string} invoice_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} currency_code @property {number} duration @property {number} exchange_rate @property {number} amount @property {string} payment_method @property {string} gateway_details @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} PaymentMethod @property {string} id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} currency_code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Price @property {string} id @property {number} amount @property {number} currency_code */

// --- 6. INVENTORY & LOGISTICS ---
/** @typedef {Object} Inventory @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} InventoryItem @property {string} id @property {string} company_id @property {string} branch_id @property {string} inventory_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {string} sku @property {string} barcode @property {string} upc @property {string} ean @property {string} manufacturer_code @property {string} serial_number @property {string} batch_number @property {string} expiration_date @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} InventoryTransaction @property {string} id @property {string} company_id @property {string} branch_id @property {string} appoint_from_type @property {string} appoint_from_id @property {string} appoint_to_type @property {string} appoint_to_id @property {string} appoint_for_type @property {string} appoint_for_id @property {string} appoint_by_type @property {string} appoint_by_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Purchase @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} PurchaseItem @property {string} id @property {string} company_id @property {string} branch_id @property {string} purchase_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {string} sku @property {string} barcode @property {string} upc @property {string} ean @property {string} manufacturer_code @property {string} serial_number @property {string} batch_number @property {string} expiration_date @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Cart @property {string} id @property {string} company_id @property {string} branch_id @property {string} cart_group_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {string} sku @property {string} barcode @property {string} upc @property {string} ean @property {string} manufacturer_code @property {string} serial_number @property {string} batch_number @property {string} expiration_date @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} CartGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 7. PROJECTS, TASKS & SERVICES ---
/** @typedef {Object} Project @property {string} id @property {string} company_id @property {string} branch_id @property {string} project_group_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} ProjectGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Task @property {string} id @property {string} company_id @property {string} branch_id @property {string} task_group_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} currency_code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} TaskGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Service @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} duration @property {string} start_at @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} ServiceGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} duration @property {string} start_at @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 8. BOOKINGS & EVENTS ---
/** @typedef {Object} Booking @property {string} id @property {string} company_id @property {string} branch_id @property {string} booking_resource_id @property {string} price_id @property {string} appoint_from_type @property {string} appoint_from_id @property {string} appoint_to_type @property {string} appoint_to_id @property {string} appoint_for_type @property {string} appoint_for_id @property {string} appoint_by_type @property {string} appoint_by_id @property {string} name @property {string} description @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} BookingResource @property {string} id @property {string} company_id @property {string} branch_id @property {string} booking_resourceable_type @property {string} booking_resourceable_id @property {string} name @property {string} description @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} BookingPeriod @property {string} id @property {string} booking_resource_id @property {string} period_id @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {Metadata} metadata */
/** @typedef {Object} Event @property {string} id @property {string} event_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} EventGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Exam @property {string} id @property {string} exam_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} ExamGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 9. FACILITIES & INFRASTRUCTURE ---
/** @typedef {Object} Facility @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} FacilityGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Address @property {string} id @property {string} line_1 @property {string} line_2 @property {string} city @property {string} state_or_province @property {string} postal_code @property {number} country_code @property {string} fingerprint */

// --- 10. CMS & DOCUMENTS ---
/** @typedef {Object} Article @property {string} id @property {string} article_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} title @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} ArticleGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} title @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Document @property {string} id @property {string} document_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} title @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} DocumentGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} title @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 11. COMMUNICATION & NOTIFICATIONS ---
/** @typedef {Object} Notification @property {string} id @property {string} notification_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} NotificationGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 12. SUBSCRIPTIONS & PLANS ---
/** @typedef {Object} Subscription @property {string} id @property {string} company_id @property {string} branch_id @property {string} subscription_plan_id @property {string} subscription_group_id @property {string} price_id @property {string} period_id @property {string} seller_type @property {string} seller_id @property {string} buyer_type @property {string} buyer_id @property {string} resource_type @property {string} resource_id @property {string} processer_type @property {string} processer_id @property {string} name @property {string} description @property {number} country_code @property {number} timezone @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {boolean} auto_renew @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} SubscriptionGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} subscription_plan_id @property {string} subscription_group_id @property {string} price_id @property {string} period_id @property {string} seller_type @property {string} seller_id @property {string} buyer_type @property {string} buyer_id @property {string} resource_type @property {string} resource_id @property {string} processer_type @property {string} processer_id @property {string} name @property {string} description @property {number} country_code @property {number} timezone @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {boolean} auto_renew @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} SubscriptionPlan @property {string} id @property {string} company_id @property {string} branch_id @property {string} price_id @property {string} name @property {string} description @property {string} code @property {number} duration_days @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {number} country_code @property {Object} features @property {Object} limits @property {string} discarded_at */
/** @typedef {Object} SystemSubscription @property {string} id @property {string} system_subscription_plan_id @property {string} system_subscription_group_id @property {string} company_id @property {string} branch_id @property {string} price_id @property {string} period_id @property {string} seller_type @property {string} seller_id @property {string} buyer_type @property {string} buyer_id @property {string} resource_type @property {string} resource_id @property {string} processer_type @property {string} processer_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {number} country_code @property {boolean} auto_renew @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} SystemSubscriptionGroup @property {string} id @property {string} system_subscription_plan_id @property {string} company_id @property {string} branch_id @property {string} price_id @property {string} period_id @property {string} seller_type @property {string} seller_id @property {string} buyer_type @property {string} buyer_id @property {string} resource_type @property {string} resource_id @property {string} processer_type @property {string} processer_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {number} country_code @property {boolean} auto_renew @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} SystemSubscriptionPlan @property {string} id @property {string} price_id @property {string} name @property {string} description @property {string} code @property {number} duration_days @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {number} country_code @property {Object} features @property {Object} limits @property {string} discarded_at @property {Metadata} metadata */

// --- 13. TAXONOMY (TAGS, CATEGORIES, BRANDS) ---
/** @typedef {Object} Category @property {string} id @property {string} company_id @property {string} name @property {string} description @property {Metadata} metadata */
/** @typedef {Object} Tag @property {string} id @property {string} company_id @property {string} name @property {string} description @property {string} code */
/** @typedef {Object} Brand @property {string} id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 14. QA & FEEDBACK ---
/** @typedef {Object} Question @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Answer @property {string} id @property {string} question_id @property {string} category_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */

// --- 15. SETTINGS & STATS ---
/** @typedef {Object} Setting @property {string} id @property {string} setting_group_id @property {string} company_id @property {string} branch_id @property {string} category_id @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} SettingGroup @property {string} id @property {string} company_id @property {string} branch_id @property {string} category_id @property {Object} content @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {Metadata} metadata */
/** @typedef {Object} Statistic @property {string} id @property {string} owner_type @property {string} owner_id @property {Object} data @property {string} recorded_at @property {Metadata} metadata */

// --- 16. TIME & PERIODS ---
/** @typedef {Object} Period @property {string} id @property {string} start_at @property {string} end_at @property {number} timezone */
/** @typedef {Object} PeriodPrice @property {string} id @property {string} period_priceable_type @property {string} period_priceable_id @property {string} period_id @property {string} price_id */

// --- 17. STORAGE (ACTIVE STORAGE) ---
/** @typedef {Object} ActiveStorageAttachment @property {string} id @property {string} name @property {string} record_type @property {string} record_id @property {string} blob_id @property {string} created_at */
/** @typedef {Object} ActiveStorageBlob @property {string} id @property {string} key @property {string} filename @property {string} content_type @property {string} metadata @property {string} service_name @property {number} byte_size @property {string} checksum @property {string} created_at */
/** @typedef {Object} ActiveStorageVariantRecord @property {string} id @property {string} blob_id @property {string} variation_digest */

// --- 18. APPOINTMENTS (POLYMORPHIC RELATIONS) ---
/** @typedef {Object} Appointment @property {string} id @property {string} appoint_from_type @property {string} appoint_from_id @property {string} appoint_to_type @property {string} appoint_to_id @property {string} appoint_for_type @property {string} appoint_for_id @property {string} appoint_by_type @property {string} appoint_by_id @property {string} name @property {string} description @property {string} code @property {number} lifecycle_status @property {number} workflow_status @property {number} business_type @property {string} discarded_at @property {string} created_at @property {string} updated_at */
/** @typedef {Appointment} AddressAppointment */
/** @typedef {Appointment} ArticleAppointment */
/** @typedef {Appointment} ArticleGroupAppointment */
/** @typedef {Appointment} CartAppointment */
/** @typedef {Appointment} CustomerAppointment */
/** @typedef {Appointment} CustomerGroupAppointment */
/** @typedef {Appointment} DepartmentAppointment */
/** @typedef {Appointment} DocumentAppointment */
/** @typedef {Appointment} DocumentGroupAppointment */
/** @typedef {Appointment} EmployeeAppointment */
/** @typedef {Appointment} EmployeeGroupAppointment */
/** @typedef {Appointment} EventAppointment */
/** @typedef {Appointment} EventGroupAppointment */
/** @typedef {Appointment} ExamAppointment */
/** @typedef {Appointment} FacilityAppointment */
/** @typedef {Appointment} FacilityGroupAppointment */
/** @typedef {Appointment} InventoryItemAppointment */
/** @typedef {Appointment} InventoryTransactionAppointment */
/** @typedef {Appointment} NotificationAppointment */
/** @typedef {Appointment} NotificationGroupAppointment */
/** @typedef {Appointment} OrderAppointment */
/** @typedef {Appointment} OrderGroupAppointment */
/** @typedef {Appointment} PaymentMethodAppointment */
/** @typedef {Appointment} PeriodAppointment */
/** @typedef {Appointment} PolicyAppointment */
/** @typedef {Appointment} PriceAppointment */
/** @typedef {Appointment} ProductAppointment */
/** @typedef {Appointment} ProductGroupAppointment */
/** @typedef {Appointment} ProjectAppointment */
/** @typedef {Appointment} ProjectGroupAppointment */
/** @typedef {Appointment} ServiceAppointment */
/** @typedef {Appointment} ServiceGroupAppointment */
/** @typedef {Appointment} SettingAppointment */
/** @typedef {Appointment} SettingGroupAppointment */
/** @typedef {Appointment} TagAppointment */
/** @typedef {Appointment} TaskAppointment */
/** @typedef {Appointment} TaskGroupAppointment */

// --- UI HELPERS ---
/** @typedef {Object} Pagination @property {number} current_page @property {number} next_page @property {number} prev_page @property {number} total_pages @property {number} total_count */

/** @type {Object} */ var Helpers;
/** @type {function(): string} */ var pathname;
/** @type {function({html: string}): void} */ var openModal;
/** @type {function(any): string} */ var identifier;
/** @type {function(any[], any, string): string} */ var selectOptionsHTML;
/** @type {function(any, string, string): any} */ var cloneNewKey;
/** @type {function(Pagination): string} */ var pagination;
/** @type {function(): Promise<any>} */ var fetchJson;