# frozen_string_literal: true

# Monthly invoice generated by Billing::InvoiceService from CalculatorService results.
# Each invoice is linked to a BillingContract and settled via BillingTransactions.
#
# Every invoice has a movement_type (deposit/charge) and target_balance
# (main_balance/promo_balance) that describe what kind of money movement this is.
#
# Payment status is derived from the sum of BillingTransactions:
#   SUM(transactions.amount_cents) >= price_cents  →  paid
#
# The BillingTransaction's after_create_commit callback keeps payment_status in sync.
#
# Invoice numbers auto-generate like "INV-202606-A1B2C3"
#
class BillingInvoice < ApplicationRecord
  attribute :price_cents, :integer, default: 0

  monetize :price_cents,
           as: "price",
           with_model_currency: :currency,
           disable_validation: true

  belongs_to :company
  belongs_to :billing_contract
  has_many :billing_transactions

  validates :invoice_number, presence: true, uniqueness: true
  validates :price_cents, presence: true, numericality: { greater_than_or_equal_to: 0 }

  enum :payment_status, { unpaid: 0, paid: 1, voided: 2, overdue: 3 }, default: :unpaid
  enum :lifecycle_status, { final: 0, draft: 1 }, default: :final

  enum :movement_type, { deposit: 0, charge: 1 }
  enum :target_balance, { main_balance: 0, promo_balance: 1 }
  enum :created_by, { system: 0, customer: 1 }
  enum :currency, CURRENCIE_CODES, prefix: true, default: :usd

  before_validation :generate_invoice_number, on: :create
  after_update :try_reactivate_company, if: -> { saved_change_to_payment_status? && paid? }
  after_create_commit :attempt_auto_settlement, if: -> { unpaid? }

  scope :deposits, -> { where(movement_type: :deposit) }
  scope :charges, -> { where(movement_type: :charge) }
  scope :main_wallet, -> { where(target_balance: :main_balance) }
  scope :promo_wallet, -> { where(target_balance: :promo_balance) }

  private

  def try_reactivate_company
    company.try_reactivate!
  end

  def attempt_auto_settlement
    company.auto_settle_unpaid_invoices
  end

  def generate_invoice_number
    return if invoice_number.present?

    date_slug = Time.current.strftime("%Y%m")
    random_slug = SecureRandom.hex(3).upcase
    self.invoice_number = "INV-#{date_slug}-#{random_slug}"
  end
end
