# Monthly invoice generated by Billing::InvoiceService from CalculatorService results.
# Each invoice is linked to the BillingContract snapshot and the company wallet.
#
# SettlementService deducts the invoice amount:
#   InvoiceService.call(company, result)  # creates BillingInvoice
#   SettlementService.call(invoice)       # deducts balances, marks paid/overdue
#
# Invoice numbers auto-generate like "INV-202606-A1B2C3"
#
class BillingInvoice < ApplicationRecord
  attribute :price_cents, :integer, default: 0
  attribute :price_currency, :string, default: "USD"

  belongs_to :company
  belongs_to :billing_contract
  has_many :wallet_transactions

  validates :invoice_number, presence: true, uniqueness: true
  validates :price_cents, presence: true, numericality: { greater_than_or_equal_to: 0 }

  enum :payment_status, { unpaid: 0, paid: 1, voided: 2, overdue: 3 }, default: :unpaid
  enum :lifecycle_status, { final: 0, draft: 1 }, default: :final

  before_validation :generate_invoice_number, on: :create
  after_update :try_reactivate_company, if: -> { saved_change_to_payment_status? && paid? }
  after_create_commit :attempt_auto_settlement, if: -> { unpaid? }

  private

  def try_reactivate_company
    company.try_reactivate!
  end

  def attempt_auto_settlement
    company.auto_settle_unpaid_invoices
  end

  def generate_invoice_number
    return if invoice_number.present?

    date_slug = Time.current.strftime("%Y%m")
    random_slug = SecureRandom.hex(3).upcase
    self.invoice_number = "INV-#{date_slug}-#{random_slug}"
  end
end
