# How to use: Dont update records, always find_or_create to reuse existing periods.
# app/models/period.rb
class Period < ApplicationRecord
  include ImmutableRecordConcern

  # 1. Define the Enum with Valid Method Names
  # We map safe names (e.g., :plus_7) to your values (7).
  enum :time_zone, {
    minus_12: -12,
    minus_11: -11,
    minus_10: -10,
    minus_9:  -9,
    minus_8:  -8,
    minus_7:  -7,
    minus_6:  -6,
    minus_5:  -5,
    minus_4:  -4,
    minus_3:  -3,
    minus_2:  -2,
    minus_1:  -1,
    utc:      0,
    plus_1:   1,
    plus_2:   2,
    plus_3:   3,
    plus_4:   4,
    plus_5:   5,
    plus_6:   6,
    plus_7:   7,
    plus_8:   8,
    plus_9:   9,
    plus_10:  10,
    plus_11:  11,
    plus_12:  12
  }, prefix: :offset # Optional: creates methods like 'offset_plus_7?'

  # 2. Validations
  validates :start_at, presence: true
  validates :time_zone, presence: true

  # Uniqueness constraint
  validates :start_at, uniqueness: {
    scope: [ :end_at, :time_zone ],
    message: "already exists with this time and offset"
  }

  # 3. Reusable Logic
  def self.reusable_create(start_at:, end_at: nil, time_zone: 0)
    # You can pass the integer (7) or the key (:plus_7)
    find_or_create_by(
      start_at: start_at,
      end_at: end_at,
      time_zone: time_zone
    )
  end

  # 4. Helper: Format the offset for display (e.g., returns "+07:00")
  def formatted_offset
    # time_zone returns the string key (e.g., "plus_7"), so we fetch the integer value
    val = Period.time_zones[time_zone]
    sign = val >= 0 ? "+" : "-"
    "#{sign}#{val.abs.to_s.rjust(2, '0')}:00"
  end
end



# # Option A: Use Integers (Easiest)
# # Rails automatically finds the enum key ":plus_7" for the value 7
# p1 = Period.reusable_period(start_at: Time.current, time_zone: 7)

# # Option B: Use Enum Keys
# p2 = Period.reusable_period(start_at: Time.current, time_zone: :plus_7)


# # --- Checking the Data ---

# puts p1.time_zone          # => "plus_7" (The enum label)
# puts p1[:time_zone]        # => 7        (The raw integer in DB)

# # Check bools (generated by Enum)
# puts p1.offset_plus_7?     # => true
# puts p1.offset_minus_5?    # => false

# # Display
# puts "Time: #{p1.start_at} (UTC#{p1.formatted_offset})"
# # => "Time: 2024-12-25 10:00:00 (UTC+07:00)"
