class Tag < ApplicationRecord
  attribute :permission_resource_name, :string, default: -> { self.name }

  belongs_to :company

  has_many :answer_tag_appointments, dependent: :destroy
  has_many :answers, through: :answer_tag_appointments
  has_many :article_tag_appointments, dependent: :destroy
  has_many :articles, through: :article_tag_appointments
  has_many :article_group_tag_appointments, dependent: :destroy
  has_many :article_groups, through: :article_group_tag_appointments
  has_many :branch_tag_appointments, dependent: :destroy
  has_many :branches, through: :branch_tag_appointments
  has_many :brand_tag_appointments, dependent: :destroy
  has_many :brands, through: :brand_tag_appointments
  has_many :company_tag_appointments, dependent: :destroy
  has_many :companies, through: :company_tag_appointments
  has_many :customer_tag_appointments, dependent: :destroy
  has_many :customers, through: :customer_tag_appointments
  has_many :customer_group_tag_appointments, dependent: :destroy
  has_many :customer_groups, through: :customer_group_tag_appointments
  has_many :department_tag_appointments, dependent: :destroy
  has_many :departments, through: :department_tag_appointments
  has_many :document_tag_appointments, dependent: :destroy
  has_many :documents, through: :document_tag_appointments
  has_many :document_group_tag_appointments, dependent: :destroy
  has_many :document_groups, through: :document_group_tag_appointments
  has_many :employee_tag_appointments, dependent: :destroy
  has_many :employees, through: :employee_tag_appointments
  has_many :employee_group_tag_appointments, dependent: :destroy
  has_many :employee_groups, through: :employee_group_tag_appointments
  has_many :event_tag_appointments, dependent: :destroy
  has_many :events, through: :event_tag_appointments
  has_many :event_group_tag_appointments, dependent: :destroy
  has_many :event_groups, through: :event_group_tag_appointments
  has_many :exam_tag_appointments, dependent: :destroy
  has_many :exams, through: :exam_tag_appointments
  has_many :exam_group_tag_appointments, dependent: :destroy
  has_many :exam_groups, through: :exam_group_tag_appointments
  has_many :facility_tag_appointments, dependent: :destroy
  has_many :facilities, through: :facility_tag_appointments
  has_many :facility_group_tag_appointments, dependent: :destroy
  has_many :facility_groups, through: :facility_group_tag_appointments
  has_many :invoice_tag_appointments, dependent: :destroy
  has_many :invoices, through: :invoice_tag_appointments
  has_many :notification_tag_appointments, dependent: :destroy
  has_many :notifications, through: :notification_tag_appointments
  has_many :notification_group_tag_appointments, dependent: :destroy
  has_many :notification_groups, through: :notification_group_tag_appointments
  has_many :order_tag_appointments, dependent: :destroy
  has_many :orders, through: :order_tag_appointments
  has_many :order_group_tag_appointments, dependent: :destroy
  has_many :order_groups, through: :order_group_tag_appointments
  has_many :product_tag_appointments, dependent: :destroy
  has_many :products, through: :product_tag_appointments
  has_many :product_group_tag_appointments, dependent: :destroy
  has_many :product_groups, through: :product_group_tag_appointments
  has_many :project_tag_appointments, dependent: :destroy
  has_many :projects, through: :project_tag_appointments
  has_many :project_group_tag_appointments, dependent: :destroy
  has_many :project_groups, through: :project_group_tag_appointments
  has_many :purchase_tag_appointments, dependent: :destroy
  has_many :purchases, through: :purchase_tag_appointments
  has_many :purchase_item_tag_appointments, dependent: :destroy
  has_many :purchase_items, through: :purchase_item_tag_appointments
  has_many :question_tag_appointments, dependent: :destroy
  has_many :questions, through: :question_tag_appointments
  has_many :role_tag_appointments, dependent: :destroy
  has_many :roles, through: :role_tag_appointments
  has_many :service_tag_appointments, dependent: :destroy
  has_many :services, through: :service_tag_appointments
  has_many :service_group_tag_appointments, dependent: :destroy
  has_many :service_groups, through: :service_group_tag_appointments
  has_many :setting_tag_appointments, dependent: :destroy
  has_many :settings, through: :setting_tag_appointments
  has_many :setting_group_tag_appointments, dependent: :destroy
  has_many :setting_groups, through: :setting_group_tag_appointments
  has_many :statistic_tag_appointments, dependent: :destroy
  has_many :statistics, through: :statistic_tag_appointments
  has_many :stock_tag_appointments, dependent: :destroy
  has_many :stocks, through: :stock_tag_appointments
  has_many :stock_export_tag_appointments, dependent: :destroy
  has_many :stock_exports, through: :stock_export_tag_appointments
  has_many :stock_import_tag_appointments, dependent: :destroy
  has_many :stock_imports, through: :stock_import_tag_appointments
  has_many :stock_transfer_tag_appointments, dependent: :destroy
  has_many :stock_transfers, through: :stock_transfer_tag_appointments
  has_many :subscription_group_tag_appointments, dependent: :destroy
  has_many :subscription_groups, through: :subscription_group_tag_appointments
  has_many :supplier_tag_appointments, dependent: :destroy
  has_many :suppliers, through: :supplier_tag_appointments
  has_many :tag_task_appointments, dependent: :destroy
  has_many :tasks, through: :tag_task_appointments
  has_many :tag_task_group_appointments, dependent: :destroy
  has_many :task_groups, through: :tag_task_group_appointments
  has_many :tag_transaction_appointments, dependent: :destroy
  has_many :transactions, through: :tag_transaction_appointments, source: :target_transaction
  has_many :tag_warehouse_appointments, dependent: :destroy
  has_many :warehouses, through: :tag_warehouse_appointments

  validates :key, presence: true, uniqueness: { scope: :company_id }
end
