name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github
        # fix: bin/rubocop --auto-correct-all 

  seed-test:
    runs-on: ubuntu-latest
    # environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      # Run docker compose that shows onlt logs from the web service and fails on test failure
      - name: Run Docker Compose and fail on test failure
        # env:
        #   RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} docker compose -p skycom-seed-test -f docker-compose.seed-test.yml up --abort-on-container-exit --exit-code-from web --attach web

      - name: Show running containers
        run: docker ps -a

      # Optional: Tear down after test
      - name: Stop and remove containers
        if: always()
        run: docker compose -p skycom-seed-test -f docker-compose.seed-test.yml down

  rspec-test:
    runs-on: ubuntu-latest
    # environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix workspace permissions for Docker bind mounts
        run: sudo chmod -R 777 .

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      # Run docker compose that shows onlt logs from the web service and fails on test failure
      - name: Run Docker Compose and fail on Rspec test failure
        # env:
        #   RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} docker compose -p skycom-rspec-test -f docker-compose.rspec-test.yml up --abort-on-container-exit --exit-code-from web --attach web

      - name: Show running containers
        run: docker ps -a

      # Optional: Tear down after test
      - name: Stop and remove containers
        if: always()
        run: docker compose -p skycom-seed-test -f docker-compose.rspec-test.yml down
